### ISSUE TITLE
Update to new endpoint

### ISSUE THREAD

**Issue by case** [kflorence/domainr-php#4]
Hey Kyle,

We're moving to a versioned endpoint, for the `/api/json` calls: `https://api.domainr.com/v1`

([updated documentation](https://github.com/domainr/api/wiki/V1-API))

We'll handle redirects from the old URL pattern for a few months, but wondering if you could update your endpoint code?

Thanks!
-Eric

**Comment by kflorence** [comment]
@case absolutely, will update it this weekend.
